import { createSlice } from "@reduxjs/toolkit";
import { combineReducers } from "redux";

export const assetSlice = createSlice({
  name: "asset",
  initialState: {
    data: [
      {
        bid: 1.28136,
        ask: 1.28138,
        spread_diff: 0,
        chart_symbol: "FX:EURUSD",
        symbol: "EURUSD",
        digits: 5,
        currency: "EUR",
        description: "Euro vs US Dollar",
        contract_size: 100000,
        percentage: 0.909,
        instrument: 0,
        volumeMin: 1,
        volumeMax: 3000,
        volumeStep: 1,
        tick_size: 0,
        tick_value: 0,
        margin_initial: 0,
        mode: 0,
        profit_mode: 0,
        group: "Commodities",
        marketState: 0,
        stops_level: 0,
        lot_currency: "EUR",
        name: "EURUSD",
        display_name: "EURUSD",
        price_open: 1.2237,
        popular: true,
        mover: 0,
        img: "https://cdn-plus.olymptrade.com/fe/293_221205151726/bundle/images/pair-icon-eurusd.img.svg",
      },
      {
        bid: 1.28136,
        ask: 1.28138,
        spread_diff: 0,
        chart_symbol: "FX:EURUSD",
        symbol: "EURUSD",
        digits: 5,
        currency: "EUR",
        description: "Euro vs US Dollar",
        contract_size: 100000,
        percentage: 0.909,
        instrument: 0,
        volumeMin: 1,
        volumeMax: 3000,
        volumeStep: 1,
        tick_size: 0,
        tick_value: 0,
        margin_initial: 0,
        mode: 0,
        profit_mode: 0,
        group: "Forex",
        marketState: 0,
        stops_level: 0,
        lot_currency: "EUR",
        name: "EURUSD",
        display_name: "EURUSD",
        price_open: 1.2237,
        popular: true,
        mover: 0,
        img: "https://cdn-plus.olymptrade.com/fe/293_221205151726/bundle/images/pair-icon-eurusd.img.svg",
      },
      {
        bid: 1.18136,
        ask: 1.18138,
        spread_diff: 0,
        chart_symbol: "FX_IDC:EURNOK",
        digits: 5,
        symbol: "EURNOK",
        currency: "EUR",
        description: "Euro vs US Dollar",
        contract_size: 100000,
        percentage: 0.909,
        instrument: 0,
        volumeMin: 1,
        volumeMax: 3000,
        volumeStep: 1,
        tick_size: 0,
        tick_value: 0,
        margin_initial: 0,
        mode: 0,
        profit_mode: 0,
        group: "Forex",
        marketState: 0,
        stops_level: 0,
        lot_currency: "EUR",
        name: "EURNOK",
        display_name: "EURUSD",
        price_open: 1.1137,
        popular: true,
        mover: 0,
        img: "https://assets.xm-cdn.com/static/research-portal/instruments_icons/eurnok.svg",
      },
      {
        bid: 54321.19,
        ask: 1.18138,
        spread_diff: 0,
        symbol: "BTCUSD",
        chart_symbol: "COINBASE:BTCUSD",
        digits: 5,
        currency: "EUR",
        description: "Euro vs US Dollar",
        contract_size: 100000,
        percentage: 0.909,
        instrument: 0,
        volumeMin: 1,
        volumeMax: 3000,
        volumeStep: 1,
        tick_size: 0,
        tick_value: 0,
        margin_initial: 0,
        mode: 0,
        profit_mode: 0,
        group: "Cryptocurrencies",
        marketState: 0,
        stops_level: 0,
        lot_currency: "EUR",
        name: "BTCUSD",
        display_name: "EURUSD",
        price_open: 55489.87,
        popular: true,
        mover: 0,
        img: "https://assets.xm-cdn.com/static/research-portal/instruments_icons/btcusd.svg",
      },
      {
        bid: 1.18136,
        ask: 1.18138,
        spread_diff: 0,
        symbol: "AUDCAD",
        chart_symbol: "FX:AUDCAD",
        digits: 5,
        currency: "EUR",
        description: "Euro vs US Dollar",
        contract_size: 100000,
        percentage: 0.909,
        instrument: 0,
        volumeMin: 1,
        volumeMax: 3000,
        volumeStep: 1,
        tick_size: 0,
        tick_value: 0,
        margin_initial: 0,
        mode: 0,
        profit_mode: 0,
        group: "Forex",
        marketState: 0,
        stops_level: 0,
        lot_currency: "EUR",
        name: "AUDCAD",
        display_name: "EURUSD",
        price_open: 1.137,
        popular: true,
        mover: 0,
        img: "https://cdn-plus.olymptrade.com/fe/293_221205151726/bundle/images/pair-icon-audcad.img.svg",
      },
      {
        bid: 1.18136,
        ask: 1.18138,
        spread_diff: 0,
        symbol: "GBPUSD",
        chart_symbol: "FX_IDC:GBPUSD",
        digits: 5,
        currency: "EUR",
        description: "Euro vs US Dollar",
        contract_size: 100000,
        percentage: 0.909,
        instrument: 0,
        volumeMin: 1,
        volumeMax: 3000,
        volumeStep: 1,
        tick_size: 0,
        tick_value: 0,
        margin_initial: 0,
        mode: 0,
        profit_mode: 0,
        group: "Forex",
        marketState: 0,
        stops_level: 0,
        lot_currency: "EUR",
        name: "GBPUSD",
        display_name: "bURUSD",
        price_open: 1.181,
        popular: true,
        mover: 0,
        img: "https://trading212equities.s3.eu-central-1.amazonaws.com/GBPUSD.png",
      },
      {
        bid: 1.18136,
        ask: 1.18138,
        symbol: "AUDCHF",
        spread_diff: 0,
        chart_symbol: "FX_IDC:AUDCHF",
        digits: 5,
        currency: "EUR",
        description: "Euro vs US Dollar",
        contract_size: 100000,
        percentage: 0.909,
        instrument: 0,
        volumeMin: 1,
        volumeMax: 3000,
        volumeStep: 1,
        tick_size: 0,
        tick_value: 0,
        margin_initial: 0,
        mode: 0,
        profit_mode: 0,
        group: "Forex",
        marketState: 0,
        stops_level: 0,
        lot_currency: "EUR",
        name: "AUDCHF",
        display_name: "bURUSD",
        price_open: 1.181,
        popular: true,
        mover: 0,
        img: "https://cdn-plus.olymptrade.com/fe/293_221205151726/bundle/images/pair-icon-audchf.img.svg",
      },
      {
        bid: 1.18136,
        ask: 1.18138,
        symbol: "AUDUSD",
        spread_diff: 0,
        chart_symbol: "FX_IDC:AUDUSD",
        digits: 5,
        currency: "EUR",
        description: "Euro vs US Dollar",
        contract_size: 100000,
        percentage: 0.909,
        instrument: 0,
        volumeMin: 1,
        volumeMax: 3000,
        volumeStep: 1,
        tick_size: 0,
        tick_value: 0,
        margin_initial: 0,
        mode: 0,
        profit_mode: 0,
        group: "Forex",
        marketState: 0,
        stops_level: 0,
        lot_currency: "EUR",
        name: "AUDUSD",
        display_name: "bURUSD",
        price_open: 1.181,
        popular: true,
        mover: 0,
        img: "https://www.spectre.ai/assets/images/assets/AUDUSD-top.svg?v=2.13",
      },
      {
        bid: 3178.22,
        ask: 1.18138,
        symbol: "ETHUSD",
        spread_diff: 0,
        chart_symbol: "COINBASE:ETHUSD",
        digits: 5,
        currency: "EUR",
        description: "Euro vs US Dollar",
        contract_size: 100000,
        percentage: 0.909,
        instrument: 0,
        volumeMin: 1,
        volumeMax: 3000,
        volumeStep: 1,
        tick_size: 0,
        tick_value: 0,
        margin_initial: 0,
        mode: 0,
        profit_mode: 0,
        group: "Cryptocurrencies",
        marketState: 0,
        stops_level: 0,
        lot_currency: "EUR",
        name: "ETHUSD",
        display_name: "bURUSD",
        price_open: 1.181,
        popular: true,
        mover: 0,
        img: "https://static.okx.com/cdn/assets/imgs/221/5F33E3F751873296.png",
      },
      {
        bid: 1.18136,
        ask: 1.18138,
        spread_diff: 0,
        symbol: "EURSEK",
        chart_symbol: "FX_IDC:EURSEK",
        digits: 5,
        currency: "EUR",
        description: "Euro vs US Dollar",
        contract_size: 100000,
        percentage: 0.909,
        instrument: 0,
        volumeMin: 1,
        volumeMax: 3000,
        volumeStep: 1,
        tick_size: 0,
        tick_value: 0,
        margin_initial: 0,
        mode: 0,
        profit_mode: 0,
        group: "Forex",
        marketState: 0,
        stops_level: 0,
        lot_currency: "EUR",
        name: "EURSEK",
        display_name: "bURUSD",
        price_open: 1.181,
        popular: true,
        mover: 0,
        img: "https://assets.xm-cdn.com/static/research-portal/instruments_icons/eursek.svg",
      },
      {
        bid: 1.18136,
        ask: 1.18138,
        spread_diff: 0,
        symbol: "USDJPY",
        chart_symbol: "FX_IDC:USDJPY",
        digits: 5,
        currency: "EUR",
        description: "Euro vs US Dollar",
        contract_size: 100000,
        percentage: 0.909,
        instrument: 0,
        volumeMin: 1,
        volumeMax: 3000,
        volumeStep: 1,
        tick_size: 0,
        tick_value: 0,
        margin_initial: 0,
        mode: 0,
        profit_mode: 0,
        group: "Forex",
        marketState: 0,
        stops_level: 0,
        lot_currency: "EUR",
        name: "USDJPY",
        display_name: "bURUSD",
        price_open: 1.181,
        popular: true,
        mover: 0,
        img: "https://assets.xm-cdn.com/static/research-portal/instruments_icons/usdjpy.svg",
      },
      {
        bid: 1.18136,
        ask: 1.18138,
        symbol: "USDCA",
        spread_diff: 0,
        chart_symbol: "FX_IDC:USDCAD",
        digits: 5,
        currency: "EUR",
        description: "Euro vs US Dollar",
        contract_size: 100000,
        percentage: 0.909,
        instrument: 0,
        volumeMin: 1,
        volumeMax: 3000,
        volumeStep: 1,
        tick_size: 0,
        tick_value: 0,
        margin_initial: 0,
        mode: 0,
        profit_mode: 0,
        group: "Forex",
        marketState: 0,
        stops_level: 0,
        lot_currency: "EUR",
        name: "USDCAD",
        display_name: "bURUSD",
        price_open: 1.181,
        popular: true,
        mover: 0,
        img: "https://cdn-plus.olymptrade.com/fe/293_221205151726/bundle/images/pair-icon-usdcad.img.svg",
      },
      {
        bid: 1.18136,
        ask: 1.18138,
        symbol: "USDCN",
        spread_diff: 0,
        chart_symbol: "FX_IDC:USDCNY",
        digits: 5,
        currency: "EUR",
        description: "Euro vs US Dollar",
        contract_size: 100000,
        percentage: 0.909,
        instrument: 0,
        volumeMin: 1,
        volumeMax: 3000,
        volumeStep: 1,
        tick_size: 0,
        tick_value: 0,
        margin_initial: 0,
        mode: 0,
        profit_mode: 0,
        group: "Forex",
        marketState: 0,
        stops_level: 0,
        lot_currency: "EUR",
        name: "USDCNY",
        display_name: "bURUSD",
        price_open: 1.181,
        popular: true,
        mover: 0,
        img: "https://is3-ssl.mzstatic.com/image/thumb/Purple7/v4/72/82/f0/7282f092-4973-d343-e214-4971cdc18ee7/source/150x150bb.jpg",
      },
      {
        bid: 1.18136,
        ask: 1.18138,
        spread_diff: 0,
        symbol: "XRPUSD",
        chart_symbol: "BITSTAMP:XRPUSD",
        digits: 5,
        currency: "EUR",
        description: "Euro vs US Dollar",
        contract_size: 100000,
        percentage: 0.909,
        instrument: 0,
        volumeMin: 1,
        volumeMax: 3000,
        volumeStep: 1,
        tick_size: 0,
        tick_value: 0,
        margin_initial: 0,
        mode: 0,
        profit_mode: 0,
        group: "Cryptocurrencies",
        marketState: 0,
        stops_level: 0,
        lot_currency: "EUR",
        name: "XRPUSD",
        display_name: "bURUSD",
        price_open: 1.181,
        popular: true,
        mover: 0,
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgrIQmDkPht2ohU-iZDo-ZsM-uf_WPRAefIheEYFthVx0QmFXuNGD2&usqp=CAU",
      },
      {
        bid: 1.18136,
        ask: 1.18138,
        spread_diff: 0,
        symbol: "ADAUSD",
        chart_symbol: "COINBASE:ADAUSD",
        digits: 5,
        currency: "EUR",
        description: "Euro vs US Dollar",
        contract_size: 100000,
        percentage: 0.909,
        instrument: 0,
        volumeMin: 1,
        volumeMax: 3000,
        volumeStep: 1,
        tick_size: 0,
        tick_value: 0,
        margin_initial: 0,
        mode: 0,
        profit_mode: 0,
        group: "Cryptocurrencies",
        marketState: 0,
        stops_level: 0,
        lot_currency: "EUR",
        name: "ADAUSD",
        display_name: "bURUSD",
        price_open: 1.181,
        popular: true,
        mover: 0,
        img: "https://dynamic-assets.coinbase.com/da39dfe3632bf7a9c26b5aff94fe72bc1a70850bc488e0c4d68ab3cf87ddac277cd1561427b94acb4b3e37479a1f73f1c37ed311c11a742d6edf512672aea7bb/asset_icons/a55046bc53c5de686bf82a2d9d280b006bd8d2aa1f3bbb4eba28f0c69c7597da.png",
      },
      {
        bid: 1.18136,
        ask: 1.18138,
        spread_diff: 0,
        symbol: "BCHUSD",
        chart_symbol: "COINBASE:BCHUSD",
        digits: 5,
        currency: "EUR",
        description: "Euro vs US Dollar",
        contract_size: 100000,
        percentage: 0.909,
        instrument: 0,
        volumeMin: 1,
        volumeMax: 3000,
        volumeStep: 1,
        tick_size: 0,
        tick_value: 0,
        margin_initial: 0,
        mode: 0,
        profit_mode: 0,
        group: "Cryptocurrencies",
        marketState: 0,
        stops_level: 0,
        lot_currency: "EUR",
        name: "BCHUSD",
        display_name: "bURUSD",
        price_open: 1.181,
        popular: true,
        mover: 0,
        img: "https://s2.coinmarketcap.com/static/img/coins/64x64/1831.png",
      },
      {
        bid: 1.18136,
        ask: 1.18138,
        spread_diff: 0,
        symbol: "DASHUSD",
        chart_symbol: "COINBASE:DASHUSD",
        digits: 5,
        currency: "EUR",
        description: "Euro vs US Dollar",
        contract_size: 100000,
        percentage: 0.909,
        instrument: 0,
        volumeMin: 1,
        volumeMax: 3000,
        volumeStep: 1,
        tick_size: 0,
        tick_value: 0,
        margin_initial: 0,
        mode: 0,
        profit_mode: 0,
        group: "Cryptocurrencies",
        marketState: 0,
        stops_level: 0,
        lot_currency: "EUR",
        name: "DASHUSD",
        display_name: "bURUSD",
        price_open: 1.181,
        popular: true,
        mover: 0,
        img: "https://s2.coinmarketcap.com/static/img/coins/64x64/131.png",
      },
      {
        bid: 1.18136,
        ask: 1.18138,
        spread_diff: 0,
        symbol: "EOSUSD",
        chart_symbol: "COINBASE:EOSUSD",
        digits: 5,
        currency: "EUR",
        description: "Euro vs US Dollar",
        contract_size: 100000,
        percentage: 0.909,
        instrument: 0,
        volumeMin: 1,
        volumeMax: 3000,
        volumeStep: 1,
        tick_size: 0,
        tick_value: 0,
        margin_initial: 0,
        mode: 0,
        profit_mode: 0,
        group: "Cryptocurrencies",
        marketState: 0,
        stops_level: 0,
        lot_currency: "EUR",
        name: "EOSUSD",
        display_name: "bURUSD",
        price_open: 1.181,
        popular: true,
        mover: 0,
        img: "https://s2.coinmarketcap.com/static/img/coins/64x64/1765.png",
      },
      {
        bid: 1.18136,
        ask: 1.18138,
        spread_diff: 0,
        symbol: "ETCUSD",
        chart_symbol: "COINBASE:ETCUSD",
        digits: 5,
        currency: "EUR",
        description: "Euro vs US Dollar",
        contract_size: 100000,
        percentage: 0.909,
        instrument: 0,
        volumeMin: 1,
        volumeMax: 3000,
        volumeStep: 1,
        tick_size: 0,
        tick_value: 0,
        margin_initial: 0,
        mode: 0,
        profit_mode: 0,
        group: "Cryptocurrencies",
        marketState: 0,
        stops_level: 0,
        lot_currency: "EUR",
        name: "ETCUSD",
        display_name: "bURUSD",
        price_open: 1.181,
        popular: true,
        mover: 0,
        img: "https://s2.coinmarketcap.com/static/img/coins/64x64/1321.png",
      },
      {
        bid: 1.18136,
        ask: 1.18138,
        spread_diff: 0,
        symbol: "AUDJPY",
        chart_symbol: "FX:AUDJPY",
        digits: 5,
        currency: "EUR",
        description: "Euro vs US Dollar",
        contract_size: 100000,
        percentage: 0.909,
        instrument: 0,
        volumeMin: 1,
        volumeMax: 3000,
        volumeStep: 1,
        tick_size: 0,
        tick_value: 0,
        margin_initial: 0,
        mode: 0,
        profit_mode: 0,
        group: "Forex",
        marketState: 0,
        stops_level: 0,
        lot_currency: "EUR",
        name: "AUDJPY",
        display_name: "bURUSD",
        price_open: 1.181,
        popular: true,
        mover: 0,
        img: "https://assets.xm-cdn.com/static/research-portal/instruments_icons/audjpy.svg",
      },
      {
        bid: 1.18136,
        ask: 1.18138,
        spread_diff: 0,
        symbol: "ABNB",
        chart_symbol: "NASDAQ:ABNB",
        digits: 5,
        currency: "EUR",
        description: "Euro vs US Dollar",
        contract_size: 100000,
        percentage: 0.909,
        instrument: 0,
        volumeMin: 1,
        volumeMax: 3000,
        volumeStep: 1,
        tick_size: 0,
        tick_value: 0,
        margin_initial: 0,
        mode: 0,
        profit_mode: 0,
        group: "Stocks",
        marketState: 0,
        stops_level: 0,
        lot_currency: "EUR",
        name: "ABNB",
        display_name: "bURUSD",
        price_open: 1.181,
        popular: true,
        mover: 0,
        img: "https://cdn3.iconfinder.com/data/icons/popular-services-brands/512/airbnb-512.png",
      },
      {
        bid: 1.18136,
        ask: 1.18138,
        spread_diff: 0,
        symbol: "NZDUSD",
        chart_symbol: "FX:NZDUSD",
        digits: 5,
        currency: "EUR",
        description: "Euro vs US Dollar",
        contract_size: 100000,
        percentage: 0.909,
        instrument: 0,
        volumeMin: 1,
        volumeMax: 3000,
        volumeStep: 1,
        tick_size: 0,
        tick_value: 0,
        margin_initial: 0,
        mode: 0,
        profit_mode: 0,
        group: "Forex",
        marketState: 0,
        stops_level: 0,
        lot_currency: "EUR",
        name: "NZDUSD",
        display_name: "bURUSD",
        price_open: 1.181,
        popular: true,
        mover: 0,
        img: "https://assets.xm-cdn.com/static/research-portal/instruments_icons/nzdusd.svg",
      },
      {
        bid: 1.18136,
        ask: 1.18138,
        spread_diff: 0,
        symbol: "CADCHF",
        chart_symbol: "FX:CADCHF",
        digits: 5,
        currency: "EUR",
        description: "Euro vs US Dollar",
        contract_size: 100000,
        percentage: 0.909,
        instrument: 0,
        volumeMin: 1,
        volumeMax: 3000,
        volumeStep: 1,
        tick_size: 0,
        tick_value: 0,
        margin_initial: 0,
        mode: 0,
        profit_mode: 0,
        group: "Forex",
        marketState: 0,
        stops_level: 0,
        lot_currency: "EUR",
        name: "CADCHF",
        display_name: "bURUSD",
        price_open: 1.181,
        popular: true,
        mover: 0,
        img: "https://www.tradedwell.com/web-trader/media/de5d6eb81739178f927235d377384224.png",
      },
      {
        bid: 1.18136,
        ask: 1.18138,
        spread_diff: 0,
        symbol: "AAPL",
        chart_symbol: "NASDAQ:AAPL",
        digits: 5,
        currency: "EUR",
        description: "Euro vs US Dollar",
        contract_size: 100000,
        percentage: 0.909,
        instrument: 0,
        volumeMin: 1,
        volumeMax: 3000,
        volumeStep: 1,
        tick_size: 0,
        tick_value: 0,
        margin_initial: 0,
        mode: 0,
        profit_mode: 0,
        group: "Stocks",
        marketState: 0,
        stops_level: 0,
        lot_currency: "EUR",
        name: "AAPL",
        display_name: "bURUSD",
        price_open: 1.181,
        popular: true,
        mover: 0,
        img: "https://www.tradedwell.com/web-trader/media/5e4f1f009edc913b5630f61aa7a39846.png",
      },
      {
        bid: 1.18136,
        ask: 1.18138,
        spread_diff: 0,
        symbol: "BOEING",
        chart_symbol: "NASDAQ:BOEING",
        digits: 5,
        currency: "EUR",
        description: "Euro vs US Dollar",
        contract_size: 100000,
        percentage: 0.909,
        instrument: 0,
        volumeMin: 1,
        volumeMax: 3000,
        volumeStep: 1,
        tick_size: 0,
        tick_value: 0,
        margin_initial: 0,
        mode: 0,
        profit_mode: 0,
        group: "Stocks",
        marketState: 0,
        stops_level: 0,
        lot_currency: "EUR",
        name: "BOEING",
        display_name: "bURUSD",
        price_open: 1.181,
        popular: true,
        mover: 0,
        img: "https://www.tradedwell.com/web-trader/media/72aa1b666d74fd11c7fcce6a60725cbf.png",
      },
      {
        bid: 1.18136,
        ask: 1.18138,
        spread_diff: 0,
        symbol: "BABA",
        chart_symbol: "NASDAQ:BABA",
        digits: 5,
        currency: "EUR",
        description: "Euro vs US Dollar",
        contract_size: 100000,
        percentage: 0.909,
        instrument: 0,
        volumeMin: 1,
        volumeMax: 3000,
        volumeStep: 1,
        tick_size: 0,
        tick_value: 0,
        margin_initial: 0,
        mode: 0,
        profit_mode: 0,
        group: "Stocks",
        marketState: 0,
        stops_level: 0,
        lot_currency: "EUR",
        name: "BABA",
        display_name: "bURUSD",
        price_open: 1.181,
        popular: true,
        mover: 0,
        img: "https://www.tradedwell.com/web-trader/media/c4465ca23dc3c5acadd861412db8d9cf.png",
      },
      {
        bid: 1.18136,
        ask: 1.18138,
        spread_diff: 0,
        symbol: "MA",
        chart_symbol: "NASDAQ:MA",
        digits: 5,
        currency: "EUR",
        description: "Euro vs US Dollar",
        contract_size: 100000,
        percentage: 0.909,
        instrument: 0,
        volumeMin: 1,
        volumeMax: 3000,
        volumeStep: 1,
        tick_size: 0,
        tick_value: 0,
        margin_initial: 0,
        mode: 0,
        profit_mode: 0,
        group: "Stocks",
        marketState: 0,
        stops_level: 0,
        lot_currency: "EUR",
        name: "MA",
        display_name: "bURUSD",
        price_open: 1.181,
        popular: true,
        mover: 0,
        img: "https://www.tradedwell.com/web-trader/media/17896907bbb61ddf8e983a08cb7a3a3a.png",
      },
      {
        bid: 1.18136,
        ask: 1.18138,
        spread_diff: 0,
        symbol: "MSFT",
        chart_symbol: "NASDAQ:MSFT",
        digits: 5,
        currency: "EUR",
        description: "Euro vs US Dollar",
        contract_size: 100000,
        percentage: 0.909,
        instrument: 0,
        volumeMin: 1,
        volumeMax: 3000,
        volumeStep: 1,
        tick_size: 0,
        tick_value: 0,
        margin_initial: 0,
        mode: 0,
        profit_mode: 0,
        group: "Stocks",
        marketState: 0,
        stops_level: 0,
        lot_currency: "EUR",
        name: "MSFT",
        display_name: "bURUSD",
        price_open: 1.181,
        popular: true,
        mover: 0,
        img: "https://www.tradedwell.com/web-trader/media/2bed397f3f062754d0a658df95063234.png",
      },
      {
        bid: 1.18136,
        ask: 1.18138,
        spread_diff: 0,
        symbol: "GOOGLE",
        chart_symbol: "NASDAQ:GOOGLE",
        digits: 5,
        currency: "EUR",
        description: "Euro vs US Dollar",
        contract_size: 100000,
        percentage: 0.909,
        instrument: 0,
        volumeMin: 1,
        volumeMax: 3000,
        volumeStep: 1,
        tick_size: 0,
        tick_value: 0,
        margin_initial: 0,
        mode: 0,
        profit_mode: 0,
        group: "Stocks",
        marketState: 0,
        stops_level: 0,
        lot_currency: "EUR",
        name: "GOOGLE",
        display_name: "bURUSD",
        price_open: 1.181,
        popular: true,
        mover: 0,
        img: "https://www.tradedwell.com/web-trader/media/90ef5f0e1c44b7dada77f7ccd44549be.png",
      },
      {
        bid: 1.18136,
        ask: 1.18138,
        symbol: "FB",
        spread_diff: 0,
        chart_symbol: "NASDAQ:FB",
        digits: 5,
        currency: "EUR",
        description: "Euro vs US Dollar",
        contract_size: 100000,
        percentage: 0.909,
        instrument: 0,
        volumeMin: 1,
        volumeMax: 3000,
        volumeStep: 1,
        tick_size: 0,
        tick_value: 0,
        margin_initial: 0,
        mode: 0,
        profit_mode: 0,
        group: "Stocks",
        marketState: 0,
        stops_level: 0,
        lot_currency: "EUR",
        name: "FB",
        display_name: "bURUSD",
        price_open: 1.181,
        popular: true,
        mover: 0,
        img: "https://www.tradedwell.com/web-trader/media/895cb03cd1ae9cb964cae1b62b3dc820.png",
      },
      {
        bid: 1.18136,
        ask: 1.18138,
        spread_diff: 0,
        symbol: "NVDA",
        chart_symbol: "NASDAQ:NVDA",
        digits: 5,
        currency: "EUR",
        description: "Euro vs US Dollar",
        contract_size: 100000,
        percentage: 0.909,
        instrument: 0,
        volumeMin: 1,
        volumeMax: 3000,
        volumeStep: 1,
        tick_size: 0,
        tick_value: 0,
        margin_initial: 0,
        mode: 0,
        profit_mode: 0,
        group: "Stocks",
        marketState: 0,
        stops_level: 0,
        lot_currency: "EUR",
        name: "NVDA",
        display_name: "bURUSD",
        price_open: 1.181,
        popular: true,
        mover: 0,
        img: "https://s3-symbol-logo.tradingview.com/nvidia.svg",
      },
      {
        bid: 1.18136,
        ask: 1.18138,
        spread_diff: 0,
        symbol: "JPM",
        chart_symbol: "NASDAQ:JPM",
        digits: 5,
        currency: "EUR",
        description: "Euro vs US Dollar",
        contract_size: 100000,
        percentage: 0.909,
        instrument: 0,
        volumeMin: 1,
        volumeMax: 3000,
        volumeStep: 1,
        tick_size: 0,
        tick_value: 0,
        margin_initial: 0,
        mode: 0,
        profit_mode: 0,
        group: "Stocks",
        marketState: 0,
        stops_level: 0,
        lot_currency: "EUR",
        name: "JPM",
        display_name: "bURUSD",
        price_open: 1.181,
        popular: true,
        mover: 0,
        img: "https://s3-symbol-logo.tradingview.com/jpmorgan-chase.svg",
      },
      {
        bid: 1.18136,
        ask: 1.18138,
        spread_diff: 0,
        symbol: "BMW",
        chart_symbol: "CAPITALCOM:BMW",
        digits: 5,
        currency: "EUR",
        description: "Euro vs US Dollar",
        contract_size: 100000,
        percentage: 0.909,
        instrument: 0,
        volumeMin: 1,
        volumeMax: 3000,
        volumeStep: 1,
        tick_size: 0,
        tick_value: 0,
        margin_initial: 0,
        mode: 0,
        profit_mode: 0,
        group: "Stocks",
        marketState: 0,
        stops_level: 0,
        lot_currency: "EUR",
        name: "BMW",
        display_name: "bURUSD",
        price_open: 1.181,
        popular: true,
        mover: 0,
        img: "https://www.tradedwell.com/web-trader/media/c52bab92d0b8c875e42326bc7f47e22e.png",
      },
      {
        bid: 1.18136,
        ask: 1.18138,
        spread_diff: 0,
        symbol: "COKE",
        chart_symbol: "NASDAQ:COKE",
        digits: 5,
        currency: "EUR",
        description: "Euro vs US Dollar",
        contract_size: 100000,
        percentage: 0.909,
        instrument: 0,
        volumeMin: 1,
        volumeMax: 3000,
        volumeStep: 1,
        tick_size: 0,
        tick_value: 0,
        margin_initial: 0,
        mode: 0,
        profit_mode: 0,
        group: "Stocks",
        marketState: 0,
        stops_level: 0,
        lot_currency: "EUR",
        name: "COKE",
        display_name: "bURUSD",
        price_open: 1.181,
        popular: true,
        mover: 0,
        img: "https://www.tradedwell.com/web-trader/media/87d691762349a394ac43326c2adda71d.png",
      },
      {
        bid: 1.18136,
        ask: 1.18138,
        spread_diff: 0,
        symbol: "TSLA",
        chart_symbol: "NASDAQ:TSLA",
        digits: 5,
        currency: "EUR",
        description: "Euro vs US Dollar",
        contract_size: 100000,
        percentage: 0.909,
        instrument: 0,
        volumeMin: 1,
        volumeMax: 3000,
        volumeStep: 1,
        tick_size: 0,
        tick_value: 0,
        margin_initial: 0,
        mode: 0,
        profit_mode: 0,
        group: "Stocks",
        marketState: 0,
        stops_level: 0,
        lot_currency: "EUR",
        name: "TSLA",
        display_name: "bURUSD",
        price_open: 1.181,
        popular: true,
        mover: 0,
        img: "https://www.tradedwell.com/web-trader/media/d85a9fd79eea32a3d75e7377b31da0e9.png",
      },
      {
        bid: 1.18136,
        ask: 1.18138,
        spread_diff: 0,
        symbol: "BERK.A",
        chart_symbol: "NASDAQ:BERK.A",
        digits: 5,
        currency: "EUR",
        description: "Euro vs US Dollar",
        contract_size: 100000,
        percentage: 0.909,
        instrument: 0,
        volumeMin: 1,
        volumeMax: 3000,
        volumeStep: 1,
        tick_size: 0,
        tick_value: 0,
        margin_initial: 0,
        mode: 0,
        profit_mode: 0,
        group: "Stocks",
        marketState: 0,
        stops_level: 0,
        lot_currency: "EUR",
        name: "BERK.A",
        display_name: "bURUSD",
        price_open: 1.181,
        popular: true,
        mover: 0,
        img: "https://s3-symbol-logo.tradingview.com/berkshire-hathaway.svg",
      },
      {
        bid: 1.18136,
        ask: 1.18138,
        symbol: "AMZN",
        spread_diff: 0,
        chart_symbol: "NASDAQ:AMZN",
        digits: 5,
        currency: "EUR",
        description: "Euro vs US Dollar",
        contract_size: 100000,
        percentage: 0.909,
        instrument: 0,
        volumeMin: 1,
        volumeMax: 3000,
        volumeStep: 1,
        tick_size: 0,
        tick_value: 0,
        margin_initial: 0,
        mode: 0,
        profit_mode: 0,
        group: "Stocks",
        marketState: 0,
        stops_level: 0,
        lot_currency: "EUR",
        name: "AMZN",
        display_name: "bURUSD",
        price_open: 1.181,
        popular: true,
        mover: 0,
        img: "https://www.tradedwell.com/web-trader/media/84306aa5618bfd78a21f2b4b870b788b.png",
      },
      {
        bid: 1.18136,
        ask: 1.18138,
        symbol: "LTCUSD",
        spread_diff: 0,
        chart_symbol: "COINBASE:LTCUSD",
        digits: 5,
        currency: "EUR",
        description: "Euro vs US Dollar",
        contract_size: 100000,
        percentage: 0.909,
        instrument: 0,
        volumeMin: 1,
        volumeMax: 3000,
        volumeStep: 1,
        tick_size: 0,
        tick_value: 0,
        margin_initial: 0,
        mode: 0,
        profit_mode: 0,
        group: "Cryptocurrencies",
        marketState: 0,
        stops_level: 0,
        lot_currency: "EUR",
        name: "LTCUSD",
        display_name: "bURUSD",
        price_open: 1.181,
        popular: true,
        mover: 0,
        img: "https://s2.coinmarketcap.com/static/img/coins/64x64/2.png",
      },
      {
        bid: 1.18136,
        ask: 1.18138,
        spread_diff: 0,
        symbol: "NEOUSD",
        chart_symbol: "COINBASE:NEOUSD",
        digits: 5,
        currency: "EUR",
        description: "Euro vs US Dollar",
        contract_size: 100000,
        percentage: 0.909,
        instrument: 0,
        volumeMin: 1,
        volumeMax: 3000,
        volumeStep: 1,
        tick_size: 0,
        tick_value: 0,
        margin_initial: 0,
        mode: 0,
        profit_mode: 0,
        group: "Cryptocurrencies",
        marketState: 0,
        stops_level: 0,
        lot_currency: "EUR",
        name: "NEOUSD",
        display_name: "bURUSD",
        price_open: 1.181,
        popular: true,
        mover: 0,
        img: "https://s2.coinmarketcap.com/static/img/coins/64x64/1376.png",
      },
      {
        bid: 1.18136,
        ask: 1.18138,
        symbol: "XMRUSD",

        spread_diff: 0,
        chart_symbol: "COINBASE:XMRUSD",
        digits: 5,
        currency: "EUR",
        description: "Euro vs US Dollar",
        contract_size: 100000,
        percentage: 0.909,
        instrument: 0,
        volumeMin: 1,
        volumeMax: 3000,
        volumeStep: 1,
        tick_size: 0,
        tick_value: 0,
        margin_initial: 0,
        mode: 0,
        profit_mode: 0,
        group: "Cryptocurrencies",
        marketState: 0,
        stops_level: 0,
        lot_currency: "EUR",
        name: "XMRUSD",
        display_name: "bURUSD",
        price_open: 1.181,
        popular: true,
        mover: 0,
        img: "https://s2.coinmarketcap.com/static/img/coins/64x64/328.png",
      },
      {
        bid: 1.18136,
        ask: 1.18138,
        spread_diff: 0,
        symbol: "DOGEUSD",
        chart_symbol: "COINBASE:DOGEUSD",
        digits: 5,
        currency: "EUR",
        description: "Euro vs US Dollar",
        contract_size: 100000,
        percentage: 0.909,
        instrument: 0,
        volumeMin: 1,
        volumeMax: 3000,
        volumeStep: 1,
        tick_size: 0,
        tick_value: 0,
        margin_initial: 0,
        mode: 0,
        profit_mode: 0,
        group: "Cryptocurrencies",
        marketState: 0,
        stops_level: 0,
        lot_currency: "EUR",
        name: "DOGEUSD",
        display_name: "bURUSD",
        price_open: 1.181,
        popular: true,
        mover: 0,
        img: "https://s2.coinmarketcap.com/static/img/coins/64x64/74.png",
      },
      {
        bid: 1.18136,
        ask: 1.18138,
        spread_diff: 0,
        symbol: "BNBUSD",
        chart_symbol: "COINBASE:BNBUSD",
        digits: 5,
        currency: "EUR",
        description: "Euro vs US Dollar",
        contract_size: 100000,
        percentage: 0.909,
        instrument: 0,
        volumeMin: 1,
        volumeMax: 3000,
        volumeStep: 1,
        tick_size: 0,
        tick_value: 0,
        margin_initial: 0,
        mode: 0,
        profit_mode: 0,
        group: "Cryptocurrencies",
        marketState: 0,
        stops_level: 0,
        lot_currency: "EUR",
        name: "BNBUSD",
        display_name: "bURUSD",
        price_open: 1.181,
        popular: true,
        mover: 0,
        img: "https://s2.coinmarketcap.com/static/img/coins/64x64/1839.png",
      },
      {
        bid: 1.18136,
        ask: 1.18138,
        spread_diff: 0,
        symbol: "SOLUSD",
        chart_symbol: "COINBASE:SOLUSD",
        digits: 5,
        currency: "EUR",
        description: "Euro vs US Dollar",
        contract_size: 100000,
        percentage: 0.909,
        instrument: 0,
        volumeMin: 1,
        volumeMax: 3000,
        volumeStep: 1,
        tick_size: 0,
        tick_value: 0,
        margin_initial: 0,
        mode: 0,
        profit_mode: 0,
        group: "Cryptocurrencies",
        marketState: 0,
        stops_level: 0,
        lot_currency: "EUR",
        name: "SOLUSD",
        display_name: "bURUSD",
        price_open: 1.181,
        popular: true,
        mover: 0,
        img: "https://s2.coinmarketcap.com/static/img/coins/64x64/5426.png",
      },
      {
        bid: 1.18136,
        ask: 1.18138,
        spread_diff: 0,
        chart_symbol: "COINBASE:VETUSD",
        digits: 5,
        symbol: "VETUSD",
        currency: "EUR",
        description: "Euro vs US Dollar",
        contract_size: 100000,
        percentage: 0.909,
        instrument: 0,
        volumeMin: 1,
        volumeMax: 3000,
        volumeStep: 1,
        tick_size: 0,
        tick_value: 0,
        margin_initial: 0,
        mode: 0,
        profit_mode: 0,
        group: "Cryptocurrencies",
        marketState: 0,
        stops_level: 0,
        lot_currency: "EUR",
        name: "VETUSD",
        display_name: "bURUSD",
        price_open: 1.181,
        popular: true,
        mover: 0,
        img: "https://s2.coinmarketcap.com/static/img/coins/64x64/3077.png",
      },
      {
        bid: 1.18136,
        ask: 1.18138,
        spread_diff: 0,
        chart_symbol: "COINBASE:TRXUSD",
        digits: 5,
        symbol: "TRXUSD",
        currency: "EUR",
        description: "Euro vs US Dollar",
        contract_size: 100000,
        percentage: 0.909,
        instrument: 0,
        volumeMin: 1,
        volumeMax: 3000,
        volumeStep: 1,
        tick_size: 0,
        tick_value: 0,
        margin_initial: 0,
        mode: 0,
        profit_mode: 0,
        group: "Cryptocurrencies",
        marketState: 0,
        stops_level: 0,
        lot_currency: "EUR",
        name: "TRXUSD",
        display_name: "bURUSD",
        price_open: 1.181,
        popular: true,
        mover: 0,
        img: "https://s2.coinmarketcap.com/static/img/coins/64x64/1958.png",
      },
    ],
  },
  reducers: {
    updateAsset: (state, action) => ({
      ...state,
      data: action.payload,
    })
  },
});

export const orderSlice = createSlice({
  name: "order",
  initialState: {
    asset: {
      bid: 1.18136,
      ask: 1.18138,
      spread_diff: 0,
      symbol: "",
      digits: 5,
      currency: "EUR",
      description: "Euro vs US Dollar",
      contract_size: 100000,
      percentage: 0.909,
      instrument: 0,
      volumeMin: 0.001,
      volumeMax: 3000,
      volumeStep: 1,
      tick_size: 0,
      tick_value: 0,
      margin_initial: 0,
      mode: 0,
      profit_mode: 0,
      group: "Forex",
      marketState: 0,
      stops_level: 0,
      lot_currency: "EUR",
      name: "",
      display_name: "AURUSD",
      price: 0,
      popular: true,
      mover: 0,
      img: "",
    },
  },

  reducers: {
    edit: (state, action) => ({
      ...state,
      asset: action.payload,
    }),

    decreaselots: (state, action) =>
      void {
        ...(state.asset.price -= 10),
      },
    increaselots: (state, action) =>
      void {
        ...(state.asset.price += 10),
      },
    increasestoplevel: (state, action) =>
      void {
        ...(state.asset.stops_level += 10),
      },
    decreasestoplevel: (state, action) =>
      void {
        ...(state.asset.stops_level -= 10),
      },
    resetstoplevel: (state, action) =>
      void {
        ...(state.asset.stops_level = 0),
      },
  },
});

export const accessSlice = createSlice({
  name: "access",
  initialState: {
    access: {
      code_token: "",
      recovery_email: "",
      token_identifier: "",

      token: "",
      uuid: "",
    },
  },
  reducers: {
    setAccessTokenUuid: (state, action) => ({
      ...state,
      access: action.payload,
    }),
    logOutandRemoveTokens: (state) => ({
      ...state,
      access: {
        code_token: "",
        recovery_email: "",
        token_identifier: "",

        token: "",
        uuid: "",
      },
    }),
  },
});

export const chartSlice = createSlice({
  name: "chart",
  initialState: {
    asset: {
      symbol: "EURUSD",
    },
    chartType: {
      value: "Select chart type"
    }
  },
  reducers: {
    changeChart: (state) => {
      state.asset.symbol = "usa";
    },
    changeType:(state, action) => {
      console.log("chartTradingType action ", action)
      state.chartType.value = action.payload
    }   
  },
});

export const groupSlice = createSlice({
  name: "group",
  initialState: {
    group: "Most Popular",
  },
  reducers: {
    changeGroup: (state, action) => {
      state.group = action.payload;
    },
  },
});

export const searchSlice = createSlice({
  name: "search",
  initialState: {
    search: "",
  },
  reducers: {
    changeSearch: (state, action) => {
      console.log(" ssss ", state)
      state.search = action.payload;
    },
  },
});

export const menuSlice = createSlice({
  name: "menu",
  initialState: {
    settings_opened: false,
  },
  reducers: {
    toggleMenu: (state, action) => {
      state.settings_opened = action.payload;
    },
  },
});

export const mobileMenuSlice = createSlice({
  name: "mobilemenu",
  initialState: {
    mobilemenu: {
      status: false,
      currentView: 2,
    },
  },
  reducers: {
    toggleMobileMenu: (state, action) => ({
      ...state,
      mobilemenu: action.payload,
    }),
    switchMobileView: (state, action) => ({
      ...state,
      mobilemenu: action.payload,
    }),
  },
});

export const profileSlice = createSlice({
  name: "profile",
  initialState: {
    profile: {
      full_name: "pushpendra kukreti",
      email: "kukretipushpendra@gmail.com",
      phone: "+91-999999999",
      currency: "INR",
      country: "INDIA",
    },
  },
  reducers: {
    setProfile: (state, action) => ({
      ...state,
      profile: action.payload,
    }),
  },
});

export const financepanelSlice = createSlice({
  name: "financepanel",
  initialState: {
    financepanel: {
      usedmargin: 0.0,
      stoploss: 0.0,
      profit: 0.0,
    },
  },

  reducers: {
    setFinPanel: (state, action) => ({
      ...state,
      financepanel: action.payload,
    }),
  },
});

export const tradecloseSlice = createSlice({
  name: "tradeclose",
  initialState: {
    transaction_id: "",
  },
  reducers: {
    setTradeCloseId: (state, action) => {
      state.transaction_id = action.payload;
    },
  },
});

export const historySlice = createSlice({
  name: "history",
  initialState: {
    history: [
      {
        open_time: 11111111,
        asset_name: 222222222,
        asset_volume: 333333333333,
        trade_type: 4444444444,
        cost: 555555555555555,
        open_price: 666666666,
        profit: 7777777777,
        leverage: 8888888888,
        stop_loss_value: 8888888888,
        stop_loss_price: 555555555,
        current_price: 4444444444,
        is_trade_open: 333333333333,
        close_time: 222222222,
        symbol: "sytb",
      },

      {
        open_time: 11111111,
        asset_name: 222222222,
        asset_volume: 333333333333,
        trade_type: 4444444444,
        cost: 555555555555555,
        open_price: 666666666,
        profit: 7777777777,
        leverage: 8888888888,
        stop_loss_value: 8888888888,
        stop_loss_price: 555555555,
        current_price: 4444444444,
        is_trade_open: 333333333333,
        close_time: 222222222,
        symbol: "sytb",
      },
    ],
  },
  reducers: {
    updateHistory: (state, action) => ({
      ...state,
      history: action.payload,
    }),
  },
});

export const openpositionSlice = createSlice({
  name: "openposition",
  initialState: {
    openposition: [
      {
        id: 0,
        open_time: 11111111,
        asset_name: 222222222,
        asset_volume: 333333333333,
        trade_type: 4444444444,
        cost: 555555555555555,
        open_price: 666666666,
        profit: 7777777777,
        leverage: 8888888888,
        stop_loss_value: 8888888888,
        stop_loss_price: 555555555,
        current_price: 4444444444,
        is_trade_open: 333333333333,
        close_time: 222222222,
        symbol: "sytb",
      },

      {
        id: 1,
        open_time: 11111111,
        asset_name: 222222222,
        asset_volume: 333333333333,
        trade_type: 4444444444,
        cost: 555555555555555,
        open_price: 666666666,
        profit: 7777777777,
        leverage: 8888888888,
        stop_loss_value: 8888888888,
        stop_loss_price: 555555555,
        current_price: 4444444444,
        is_trade_open: 333333333333,
        close_time: 222222222,
        symbol: "sytb",
      },
    ],
  },
  reducers: {
    updateOpenPosition: (state, action) => ({
      ...state,
      openposition: action.payload,
    }),
  },
});

const reducer = combineReducers({
  asset: assetSlice.reducer,
  order: orderSlice.reducer,
  chart: chartSlice.reducer,
  group: groupSlice.reducer,
  search: searchSlice.reducer,
  menu: menuSlice.reducer,
  access: accessSlice.reducer,
  profile: profileSlice.reducer,
  financepanel: financepanelSlice.reducer,
  openposition: openpositionSlice.reducer,
  history: historySlice.reducer,
  tradeclose: tradecloseSlice.reducer,
});

export const { updateAsset } = assetSlice.actions;
export const {
  edit,
  increaselots,
  decreaselots,
  increasestoplevel,
  decreasestoplevel,
  resetstoplevel,
} = orderSlice.actions;
export const { changeChart , changeType } = chartSlice.actions;
export const { changeSearch } = searchSlice.actions;
export const { changeGroup } = groupSlice.actions;
export const { toggleMenu } = menuSlice.actions;
export const { toggleMobileMenu, switchMobileView } = mobileMenuSlice.actions;
export const { setAccessTokenUuid } = accessSlice.actions;
export const { setProfile } = profileSlice.actions;
export const { setFinPanel } = financepanelSlice.actions;
export const { updateHistory } = historySlice.actions;
export const { updateOpenPosition } = openpositionSlice.actions;
export const { setTradeCloseId } = tradecloseSlice.actions;
export default reducer;
